name: 'Run Busted tests in Mudlet'
description: 'Run any busted spec files in your project within Mudlet'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  mudletVersion:
    description: 'Version of Mudlet to use'
    required: false
    default: 'LATEST'
  pretestPackage:
    description: 'Path to a package to install prior to running tests in Mudlet'
    required: false
    default: 'NONE'
  testsDirectory:
    description: 'Path to a directory including your tests'
    required: false
    default: ${{ github.workspace }}/build/tmp/
runs:
  using: "composite"
  steps:
    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.1.5"
      
    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: install busted
      run: |
        luarocks install busted
      shell: bash
    
    - name: Set Mudlet version
      run: ${{ github.action_path }}/set-mudlet-version.sh ${{ inputs.mudletVersion }}
      shell: bash

    - name: Restore cached Mudlet.AppImage
      uses: actions/cache@v3
      id: cache-mudlet
      with:
        path: /tmp/Mudlet.AppImage
        key: ${{ env.MUDLET_VERSION }}
    
    - name: download Mudlet
      if: steps.cache-mudlet.outputs.cache-hit != 'true'
      run: ${{ github.action_path }}/download-mudlet.sh ${{ env.MUDLET_VERSION }}
      shell: bash
    
    - name: Copy testing profile into place
      run: mkdir -p $HOME/.config/mudlet/profiles && cp -r ${{ github.action_path }}/profiles/GithubTests $HOME/.config/mudlet/profiles/
      shell: bash
    
    - name: run tests
      uses: GabrielBB/xvfb-action@v1.6
      with:
        run: /tmp/Mudlet.AppImage --profile "GithubTests" --mirror
      env:
        AUTORUN_BUSTED_TESTS: 'true'
        TESTS_DIRECTORY: ${{ inputs.testsDirectory }}
        QUIT_MUDLET_AFTER_TESTS: 'true'
        PRETEST_PACKAGE: ${{ inputs.pretestPackage }}
      
    - name: Passed Lua tests
      run: |
        if [ -e /tmp/busted-tests-failed ]
        then
          echo "Lua tests failed - see the action above for detailed output."
          exit 1
        fi
      shell: bash